enable-magisk-update = true
parallel-jobs = 1

# ReVanced Extended
[YouTube-RVX]
enabled = true
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
build-mode = "both"
version = "latest"
included-patches = "'Visual preferences icons' 'Return YouTube Username' 'Settings for YouTube' 'Theme' 'MaterialYou'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube'"
patcher-args = "--legacy-options=patch-options.json"



# ReVanced Extended
[YouTube-Monet-RVX]
enabled = true
app-name = "YouTube-Monet"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
build-mode = "both "
version = "latest"
included-patches = "'Visual preferences icons' 'Return YouTube Username' 'Settings for YouTube' 'MaterialYou'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Theme'"
patcher-args = "--legacy-options=patch-options.json"



# ReVanced Extended
[YouTube-Music-RVX]
enabled = true
app-name = "YouTube-Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
arch = "both"
build-mode = "both"
version = "latest"
included-patches = "'Hide player overlay filter' 'Settings for YouTube Music'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Dark theme'"
patcher-args = "--legacy-options=patch-options-music.json"



# ReVanced Extended
[YouTube-Music-Monet-RVX]
enabled = true
app-name = "YouTube-Music-Monet"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
arch = "both"
build-mode = "both "
version = "latest"
included-patches = "'Hide player overlay filter' 'Settings for YouTube Music' 'Dark theme'"
excluded-patches = "'Custom branding icon for YouTube Music'"
patcher-args = "--legacy-options=patch-options-music.json"